blank_issues_enabled: false
contact_links:
  - name: Purpur Discord
    url: https://purpurmc.org/discord
    about: If you are having issues with Spark profiling or have other issues, come join our Discord server for help!
    
